name: scan
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  #网络请求库 https://pub.dev/packages/dio
  dio: ^3.0.10
  #本地轻量存储 https://pub.dev/packages/shared_preferences
  shared_preferences: ^0.5.10
  #数据库
  sqflite: ^1.3.0
  #轮播图 https://pub.dev/packages/flutter_swiper
  flutter_swiper: ^1.1.6
  #路由管理 https://pub.dev/packages/fluro
  fluro: 1.6.3
  #loading https://pub.dev/packages/flutter_spinkit
  flutter_spinkit: ^4.1.2
  #toast https://pub.dev/packages/fluttertoast
  #picker选择器 https://pub.dev/packages/flutter_picker
  flutter_picker:
    git: git://github.com/yangyxd/flutter_picker.git
  #启动URL，网络电话，短信等 https://pub.dev/packages/url_launcher
  url_launcher: ^5.5.2
  #事件总线
  event_bus: ^1.1.1
  #状态管理 https://pub.flutter-io.cn/packages/provider
  provider: ^4.3.2
  #json序列化 https://pub.dev/packages/json_serializable
  json_serializable: ^3.4.1
  rxdart: ^0.24.1
  barcode_scan: ^3.0.1
  fluttertoast: ^3.1.3 #toast
  device_info: ^0.4.0+1 #获取设备信息
  flutter_cipher: ^0.0.3 #rsa 加密
  encrypt: ^4.0.0
  scan_plugin:
    git: http://192.168.66.253:9010/android/scan_plugin.git
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
